version: '3'
services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    # ports:
    #   - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
      - ./etc/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 123456
      MYSQL_RANDOM_ROOT_PASSWORD: 123456
    volumes:
      - ./var/lib/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      # - PMA_ARBITRARY=1
      PMA_USER: wordpress
      PMA_PASSWORD: 123456
      UPLOAD_LIMIT: "10M"

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
      # - 443:443
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - php
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./var/log/nginx:/var/log/nginx
      - ./www:/usr/share/nginx/www

  php:
    image: php:7.4.33-fpm
    container_name: php
    restart: always
    # ports:
    #   - 9000:9000
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./www:/usr/share/nginx/www
      - ./etc/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
