#version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui
    container_name: open-webui
    restart: always
    ports:
      - 4000:8080
    volumes:
      - open-webui:/app/backend/data
    # environment:
      #- OLLAMA_BASE_URL=http://192.168.0.197:11434/api
      #- WEBUI_SECRET_KEY=TkjGEiQ@5K^j
      # - HF_ENDPOINT=https://hf-mirror.com
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  open-webui: